### ISSUE TITLE
Hide number of contributions

### ISSUE THREAD

**Issue by dgarcia360** [dgarcia360/sphinxcontrib-ghcontributors#4]
Add the option to enable/disable the number of commits done by a contributor.

**Comment by mdurrani808** [comment]
Any updates on this?

**Comment by dgarcia360** [comment]
Hi @mdurrani808, this issue has not been implemented yet. Please, let me know if you want to take the issue.

It should be possible to hide the value by adding a [new option](https://github.com/dgarcia360/sphinxcontrib-ghcontributors/blob/master/sphinxcontrib/ghcontributors.py#L18) for the directive  and conditionally display or not the number of contributions [here](https://github.com/dgarcia360/sphinxcontrib-ghcontributors/blob/master/sphinxcontrib/models.py#L22)
